'use strict';

/**
 * Skip compose contract plumbing (scripts/check-skip-compose-contract.js).
 * These tests cover the pure verdict + the spawn plumbing with an injected
 * runner; the REAL-CLI execution lives in after-pack (dist path) and the
 * standalone script — a mocked spawn here proves wiring, never CLI semantics.
 */

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const {
  CANARY_ID,
  INSTALL_ID,
  composeContractProblems,
  composeContractRounds,
  runSkipComposeContract,
} = require('../../scripts/check-skip-compose-contract');

test('composeContractProblems demands positive evidence before canary absence', () => {
  // Healthy skip dump: install row present, canary gone.
  assert.deepEqual(composeContractProblems('skip', `- id: ${INSTALL_ID}\n`), []);
  // Healthy full dump: both present.
  assert.deepEqual(
    composeContractProblems('full', `- id: ${CANARY_ID}\n- id: ${INSTALL_ID}\n`),
    [],
  );
  // Empty/truncated dump must fail on the missing install row, not pass
  // because the canary vanished with everything else.
  const empty = composeContractProblems('skip', '');
  assert.equal(empty.length, 1);
  assert.match(empty[0], new RegExp(INSTALL_ID));
  // Skip round that still composes the user layer is the core violation.
  const resurrect = composeContractProblems('skip', `- id: ${INSTALL_ID}\n- id: ${CANARY_ID}\n`);
  assert.equal(resurrect.length, 1);
  assert.match(resurrect[0], /--skip-user-plugins 未生效/);
  // Full round without the canary means the canary probe itself is broken.
  const brokenProbe = composeContractProblems('full', `- id: ${INSTALL_ID}\n`);
  assert.equal(brokenProbe.length, 1);
  assert.match(brokenProbe[0], /canary/);
});

test('composeContractRounds keeps the desktop launcher-flag order', () => {
  const rounds = composeContractRounds('/h/apps/cli/lib/bin.js', '/p/skip.yml');
  assert.deepEqual(rounds.map((row) => row.round), ['skip', 'full']);
  assert.deepEqual(rounds[0].args, [
    '/h/apps/cli/lib/bin.js', 'web', '--skip-user-plugins', '--patch', '/p/skip.yml', '--dump-config',
  ]);
  assert.deepEqual(rounds[1].args, ['/h/apps/cli/lib/bin.js', 'web', '--dump-config']);
});

function fakeHarnessRoot(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'contract-harness-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  fs.mkdirSync(path.join(root, 'apps', 'cli', 'lib'), { recursive: true });
  fs.writeFileSync(path.join(root, 'apps', 'cli', 'lib', 'bin.js'), '// stub, never executed\n');
  return root;
}

test('runSkipComposeContract seeds a throwaway home, sanitized env, and real desktop overlays', (t) => {
  const root = fakeHarnessRoot(t);
  const calls = [];
  const result = runSkipComposeContract(root, {
    spawnSync: (nodeBin, args, options) => {
      calls.push({ nodeBin, args, options });
      const skip = args.includes('--skip-user-plugins');
      return { status: 0, stdout: skip ? `- id: ${INSTALL_ID}\n` : `- id: ${CANARY_ID}\n- id: ${INSTALL_ID}\n` };
    },
  });
  assert.deepEqual(result, { ok: true, rounds: 2 });
  assert.equal(calls.length, 2);
  const [skipCall, fullCall] = calls;
  assert.equal(skipCall.args[0], path.join(root, 'apps', 'cli', 'lib', 'bin.js'));
  assert.equal(skipCall.args[1], 'web');
  assert.equal(skipCall.args[2], '--skip-user-plugins');
  assert.equal(skipCall.args[3], '--patch');
  // The overlay is generated by the REAL ensureDesktopInstallPlugin inside the temp home.
  const home = skipCall.options.env.DSH_HOME;
  assert.ok(home && home.startsWith(os.tmpdir()));
  assert.equal(
    skipCall.args[4],
    path.join(home, 'profiles', 'web', 'desktop-plugins', 'install-dsh-plugin', 'skip-user-plugins.patch.yml'),
  );
  assert.equal(skipCall.args[5], '--dump-config');
  // dsh-home rule: the child composes only against the throwaway home.
  assert.equal(skipCall.options.env.DSHD_HOME, undefined);
  assert.equal(skipCall.options.env.DSH_HARNESS_ROOT, undefined);
  assert.deepEqual(fullCall.args.slice(1), ['web', '--dump-config']);
  // The throwaway home is removed after the run.
  assert.equal(fs.existsSync(home), false);
});

test('runSkipComposeContract fails on user-layer resurrection under skip', (t) => {
  const root = fakeHarnessRoot(t);
  assert.throws(
    () => runSkipComposeContract(root, {
      spawnSync: () => ({ status: 0, stdout: `- id: ${INSTALL_ID}\n- id: ${CANARY_ID}\n` }),
    }),
    /--skip-user-plugins 未生效/,
  );
});

test('runSkipComposeContract surfaces a nonzero dump-config exit with stderr', (t) => {
  const root = fakeHarnessRoot(t);
  assert.throws(
    () => runSkipComposeContract(root, {
      spawnSync: () => ({ status: 1, stdout: '', stderr: 'dsh: cannot resolve profile bundle "@deepseek-ai/dsh-web-app"' }),
    }),
    (error) => {
      assert.match(String(error.message), /退出码 1/);
      assert.match(String(error.message), /cannot resolve profile bundle/);
      return true;
    },
  );
});

test('runSkipComposeContract refuses a runtime without the built CLI', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'contract-empty-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  assert.throws(() => runSkipComposeContract(root), /缺少已构建的 CLI/);
});
